Repository ElemeFE/element-angular, pull requests merged in 2018-03, with the labels that each got.

#42 fix: fix form patch
  ex/docs/changelog.json
  ex/docs/col.json
  package-lock.json
  package.json
  src/col/col.directive.ts
  src/radio/radio-group.ts
Labels: bug, want merge

#51 fix(table): fix center style
  src/table/children/header.ts
Labels: bug

#54 fix: fix table binding
  ex/docs/changelog.json
  package.json
  src/table/children/body.ts
  src/table/table.ts
Labels: bug, want merge

#55 fix(table): fix column sort issue when hidden column index undefined
  src/table/table.ts
Labels: bug, need review, want merge

#59 fix(pagination): fix model empty
  ex/docs/changelog.json
  package.json
  src/pagination/pagination.ts
Labels: bug, want merge

#60 fix(table): fix partial model table row layout
  src/table/table.ts
Labels: bug, want merge

#62 fix(select): fix select writable state
  src/select/select.ts
Labels: bug, want merge

#63 fix(message): fix message animation
  src/message/message.animation.ts
  src/message/message.ts
Labels: bug, want merge

#64 build: v0.6.6
  ex/docs/changelog.json
  package-lock.json
  package.json
Labels: want merge

#66 fix(table): fix table do-check when missing slot
  ex/docs/changelog.json
  package-lock.json
  package.json
  src/table/table.ts
Labels: bug, want merge

#70 feat(select): append multiple attr
  ex/app/form/select/code.ts
  ex/app/form/select/select.component.html
  ex/app/form/select/select.component.ts
  ex/docs/changelog.json
  ex/docs/select.json
  package-lock.json
  package.json
  src/select/option.ts
  src/select/select-props.ts
  src/select/select.ts
  src/tag/tag.ts
Labels: feature, want merge

#72 fix(tree): fix tree event
  src/tree/tree-item.ts
Labels: bug, want merge

#74 build(pkg): v0.7.1
  ex/docs/changelog.json
  package-lock.json
  package.json
  src/select/select.ts
Labels: bug, enhancement, want merge

#75 build(pkg): v0.7.2
  ex/docs/changelog.json
  package-lock.json
  package.json
  src/select/select.ts
Labels: bug, want merge
