Repository ElemeFE/element-angular, pull requests merged in 2018-02, with the labels that each got.

#24 feat(container): add container directive
  ex/app/basic/container/code.ts
  ex/app/basic/container/container.component.html
  ex/app/basic/container/container.component.ts
  ex/docs/changelog.json
  ex/docs/container.json
  ex/docs/en-US/cascader.json
  ex/docs/en-US/changelog.json
  ex/docs/en-US/container.json
  ex/docs/en-US/loading.json
  ex/docs/en-US/menu-item.json
  ex/docs/en-US/table-column.json
  ex/docs/en-US/tree.json
  package-lock.json
  package.json
  src/container/children/aside.ts
  src/container/children/footer.ts
  src/container/children/header.ts
  src/container/children/main.ts
  src/container/container.directive.ts
  src/container/container.ts
  src/container/directives/aside.directive.ts
  src/container/directives/footer.directive.ts
  src/container/directives/header.directive.ts
  src/container/directives/index.ts
  src/container/directives/main.directive.ts
  src/container/module.ts
Labels: bug, enhancement, want merge

#25 fix(container): fix example
  ex/app/basic/container/code.ts
Labels: bug

#30 fix(input): fix icon event in form namespace
  ex/docs/changelog.json
  ex/docs/input.json
  package-lock.json
  package.json
  src/input/input-props.ts
  src/input/input.ts
Labels: bug, need review, want merge

#33 style(dropdown): remove log
  src/dropdown/dropdown.ts
Labels: want merge

#32 增加了一个flag可以选择是否让dropmenu中的亚洲字符不强制换行
  ex/docs/dropdown.json
  src/dropdown/dropdown.props.ts
  src/dropdown/dropdown.ts
Labels: feature

#36 fix(pagination): fix total watch
  ex/docs/changelog.json
  ex/docs/en-US/changelog.json
  ex/docs/en-US/dropdown.json
  ex/docs/en-US/input.json
  package.json
  src/dropdown/dropdown.ts
  src/pagination/children/button.ts
  src/pagination/children/pager.ts
  src/pagination/pagination.ts
Labels: bug, enhancement
